OFZ-22 feat: 리캡 Title, Non data일때 처리 & 정보제공 대시보드 UI
WORK-NECTOR/OFFIZZ-FE pull request #10
Opened 2024-08-17 08:31 UTC by yeonsuu21

## 🍋 PR 요약
리캡 
- Title 확장
- non data일때 처리
대시보드
- tab 컴포넌트 생성
- 큐레이션 페이지 생성 및 UI작업
- 큐레이션 페이지 하단 shop리스트 컴포넌트 UI

## ✨ PR 상세 내용
리캡 부분 데이터 연결은 다음 PR이나 추후 정보제공 대시보드 UI 완료 된 후 올릴것 같습니다
대시보드 부분 검색창 빼고 UI완료 되었습니다

## 🚨 주의 사항
- 코드가 매우.. 더럽습니다... 일단 산출물 구현이 먼저다보니 현 상황에서는 신경쓴 코드 작업을 하지 못할것이라 판단하였고 코드가.. 매우 더러움 주의 입니다.. 
- 상수화 : 데이터로 받는것들이 대부분이라 일단은 하드코딩으로 박아놓았습니다
- page.tsx에 간단한 컴포넌트 구조를 만들어놓아서 쓰는 형식으로 구현했습니다. 컴포넌트의 기준은 다른 페이지에서 쓰여지는것 , 여러번 map되는 형식을 기준으로 삼았고 , 그 이외에는 아마 page에서 함수로 만들어 컴포넌트처럼 쓰는것으로 구현 할 것 같습니다 ! 

- 다음 계획은 상세페이지 작업 할것같습니다 !
## 📸 스크린샷
<img width="1512" alt="스크린샷 2024-08-17 오후 5 00 32" src="https://github.com/user-attachments/assets/75cfa5b3-9856-430b-a678-925d61e3e754">
<img width="1512" alt="스크린샷 2024-08-17 오후 5 01 07" src="https://github.com/user-attachments/assets/7a4f4b9e-4227-4c89-b8e0-760775bdaca8">
<img width="1512" alt="스크린샷 2024-08-17 오후 5 01 19" src="https://github.com/user-attachments/assets/6cc21ebd-a326-47ab-843b-3b4421d0aab6">
<img width="1512" alt="스크린샷 2024-08-17 오후 5 18 46" src="https://github.com/user-attachments/assets/839edd33-93ad-4f66-b5d1-9d6a47c9e36c">
<img width="433" alt="스크린샷 2024-08-17 오후 5 18 54" src="https://github.com/user-attachments/assets/a5913328-ca87-4253-8ce1-f1eb111bd09e">

## ✅ 체크 리스트

- [ ] 리뷰어 설정했나요?
- [ ] Label 설정했나요?
- [ ] 제목 양식 맞췄나요? (ex. RAC-1 feat: 기능 추가)
- [ ] 변경 사항에 대한 테스트 진행했나요?
- [ ] `npm run format:fix` 실행했나요?

2024-08-17 13:07 UTC, leehyewon0531 requested changes
깔끔한 구조보다 기능 구현이 우선이라는 거 저도 동의하지만 저는 약간 시기상조라고 생각합니다...🥹 api 연결도 아직 안 된 상태인데 지금 단계에서 코드 가독성이나 컴포넌트화를 포기해버리면 오히려 나중에 재사용할 수 있는 컴포넌트가 없어서 다 새로 만들어야 하고 오류가 발생할 가능성도 높아질 거라고 생각합니다... 제 기억으로 공모전에 웹사이트를 제출할 때 사용 가능한 아이디/비밀번호도 같이 제공해서 심사위원단이 웹사이트를 이용할 수 있게 하는 걸로 아는데, 그래서 오류 발생 가능성도 면밀히 검토해야 할 것 같습니다ㅠㅠ,, 힘들겠지만 코드를 설계할 때 좀 더 고민하고 나중에 편한 길이 더 낫지 않을까요?! 최소한의 코드 퀄리티는 챙겨 가는 게 생산성에도 더 좋다고 생각합니다...🥹🥹

2024-08-17 13:07 UTC, leehyewon0531 commented on src/types/titleDesc.type.ts
>    sort?: SortMethod;
sort 저번에 optional로 바꾸신 거 깜빡하신 것 같습니다!! optional 하지 않는 프로퍼티로 바꿔주세요!! (제가 optional이 아니라 필수 속성이라고 생각하고 짜서 optional에 대한 대비가 안 되어 있습니다)

2024-08-17 13:10 UTC, yeonsuu21 commented on src/components/TitleContent/TitleContent.tsx
어머..! 이거 삭제했었던 기억이있는데 브랜치 파면서 다시 나왔나..? 삭제하겠습니다!

2024-08-17 13:11 UTC, yeonsuu21 commented on src/app/Information/page.tsx
넵!

2024-08-17 13:14 UTC, yeonsuu21 commented on src/app/Information/quration/page.tsx
> +function Category() {
오 그것도 괜찮은방법같습니다 ~! 변경하고 그 페이지에서만 재사용 되는것들을 하위로 따로 빼서 작업하는걸루 합시당 !!

2024-08-17 13:20 UTC, yeonsuu21 commented on src/components/TitleDesc/TitleDesc.styled.ts
> +    line-height: 3.5rem;
제 생각도 1번이 좋아보입니다! 변경하겠습니다 !

2024-08-17 13:21 UTC, yeonsuu21 commented on src/types/titleDesc.type.ts
>    sort?: SortMethod;
넵 !

2024-08-17 13:22 UTC, yeonsuu21 commented
> 깔끔한 구조보다 기능 구현이 우선이라는 거 저도 동의하지만 저는 약간 시기상조라고 생각합니다...🥹 api 연결도 아직 안 된 상태인데 지금 단계에서 코드 가독성이나 컴포넌트화를 포기해버리면 오히려 나중에 재사용할 수 있는 컴포넌트가 없어서 다 새로 만들어야 하고 오류가 발생할 가능성도 높아질 거라고 생각합니다... 제 기억으로 공모전에 웹사이트를 제출할 때 사용 가능한 아이디/비밀번호도 같이 제공해서 심사위원단이 웹사이트를 이용할 수 있게 하는 걸로 아는데, 그래서 오류 발생 가능성도 면밀히 검토해야 할 것 같습니다ㅠㅠ,, 힘들겠지만 코드를 설계할 때 좀 더 고민하고 나중에 편한 길이 더 낫지 않을까요?! 최소한의 코드 퀄리티는 챙겨 가는 게 생산성에도 더 좋다고 생각합니다...🥹🥹

저도 api 연결에 대해서 생각해보니 그래도 최대한 깔끔한 코드로 챙겨가는게 좋을것같습니다...!! 
그래서 페이지 내에서 생기는 컴포넌트로 빼고싶은 부분들은 페이지 내에 컴포넌트 폴더를 넣어서 작업하는 형식으로 할 것 같습니다 ! 감사합니다 🫡

2024-08-19 13:33 UTC, leehyewon0531 reviewed
사소한 거 2개만 남겨두었습니다!!! 수고하셨습니다 ㅠㅠㅠ ㅠ!!!!!

2024-08-19 13:33 UTC, leehyewon0531 commented on src/components/TitleDesc/TitleDesc.styled.ts
> +export const TitleDescContainer = styled.div<{ $sort: SortMethod,themeName: string }>`
styled-components의 props는 이름 앞에 `$`를 붙여주는 게 관행이라 이것만 수정해 주시면 될 것 같습니다!!ㅎㅎㅎ

2024-08-19 13:33 UTC, leehyewon0531 commented on src/types/titleDesc.type.ts
>    sort?: SortMethod;
이거 sort optional하지 않은 값으로 바꿔주세요!! 🤗🤗

2024-08-19 23:18 UTC, merged