OFZ-51 feat: 마이페이지 ui, focus 시간 로직 수정, 대시보드 vacation 모달 구현, 회고 ui
WORK-NECTOR/OFFIZZ-FE pull request #47
Opened 2024-10-06 13:21 UTC by yeonsuu21

## 🍋 PR 요약
마이페이지 ui, focus 시간 로직 수정, 대시보드 vacation 모달 구현
## ✨ PR 상세 내용
- 마이페이지 ui : api연결은 다음주쯤 할것같습니다 ! , 탈퇴부분은 로직구현은 후순위이고 버튼명만 만들어놓기로 했습니다
- focus 시간 로직 수정 : 진입하자마자 시간이 흐르고 , 중지 , 종료시 api 요청보내게 구현했습니다
- 대시보드 vacation 모달 구현 : vacation만을 위한 모달컴포넌트를 따로 만들었습니다. 하나의 모달 컴포넌트로 관리하고싶은데 시간이 많이 들것같아서 일단은 따로 구현했습니다. 조회, 생성 기능을 가진 모달입니다. 
- timeRange의 props TimeArr 수정 : 서버에서 진행하지않는 todo사항까지 null로 보내주고있어서 수정 요청했습니다.
timeRange에서 받는 키값으로 수정, 00:00:00 형식으로 서버에서 오는거 00:00으로 형식 수정했습니다
- 대시보드 회고 부분 ui : 작성 버튼 누르면 형식까지 변하게 해놨습니다 . 이. 부분에서 eslint오류가 나는데 button이 아닌 div에서 onClick을 해서 생기는 문제같습니다. 추후에 작업하실때 디자인 보면서 작업하셔야할것같아서 남깁니다 !
해결은 div가 아닌 button 태그로 바꾸면 됩니다
## 🚨 주의 사항
eslint 오류
- getAccessToken 의존성 추가 :: 해당부분 추가하니 계속 요청을 보내서 일단은 보류하고 다음주 수요일전으로 해결해보겠습니다 ㅜㅜ
- Html 써서 오류 :: 해당 부분은 상수화 해서 해결해야할것같은데 일단 기능이 우선이라고 생각 들어서 배포전까지 해결해보겠슴다 ㅜㅜ
- <img>오류:: next.js에서 제공하는 Image태그 안써서 그런것같은데 Image태그는 string을 받지 않는 오류가 나서 img로 해놓고 더 알아봐야할것같습니다 ㅜ
- 디자인 관련 : 디자인 간격이 살짝 다른부분이 있는데 목 ~ 금요일 중으로 오류해결,기능 구현 우선으로 하고 디자인 간격 다 조정할 예정입니다. 감안하고 봐주세요 !! 
- 디자인시스템, 상수화 관련: 월~수 중에 상수화는 진행할것같고 디자인시스템대로 컬러 수정하는건....... 후순위라고 생각이 드는데 일단은.... ...보기 좀 그러면 바꾸겠슴다 !! 😘🫡

😭대체적으로 스파게티 똥망 코드에요... 기능은 잘 굴러가니... 감안해서 봐주십셔 ... 😭
## 📸 스크린샷
<img width="1512" alt="스크린샷 2024-10-06 오후 9 56 58" src="https://github.com/user-attachments/assets/9bc7813d-55fd-4bbb-84ad-5c37f55fa164">
<img width="1512" alt="스크린샷 2024-10-06 오후 9 57 08" src="https://github.com/user-attachments/assets/01f6cd13-69c7-4720-885a-6e1b69199694">
<img width="395" alt="스크린샷 2024-10-06 오후 9 57 15" src="https://github.com/user-attachments/assets/ed4a94f3-08e6-49f5-9ff1-2c725ee52683">
<img width="1512" alt="스크린샷 2024-10-06 오후 9 57 24" src="https://github.com/user-attachments/assets/212d242c-5b57-49e2-b78c-2905a4690e92">
<img width="1512" alt="스크린샷 2024-10-06 오후 9 57 32" src="https://github.com/user-attachments/assets/ef1c250e-7266-4778-8566-648b86fec19f">
<img width="1512" alt="스크린샷 2024-10-06 오후 9 57 44" src="https://github.com/user-attachments/assets/779fc576-7b7e-4e53-9dd7-49a4b8b73c67">
<img width="1512" alt="스크린샷 2024-10-06 오후 9 57 54" src="https://github.com/user-attachments/assets/4c478e2c-0c2d-4c0a-8bc5-a7b9fa0257a5">
<img width="1512" alt="스크린샷 2024-10-06 오후 9 58 19" src="https://github.com/user-attachments/assets/66c3777f-3512-467a-b46f-5fb9a380457e">
<img width="468" alt="스크린샷 2024-10-06 오후 9 58 37" src="https://github.com/user-attachments/assets/a6c80bd0-7af9-4843-9154-8a4e84d0c77b">
<img width="398" alt="스크린샷 2024-10-06 오후 9 58 46" src="https://github.com/user-attachments/assets/207f2090-18e6-4778-b28d-a62974e984a5">
<img width="1512" alt="스크린샷 2024-10-06 오후 9 58 55" src="https://github.com/user-attachments/assets/32d211df-ffb0-436f-ab75-6317afde716f">
<img width="1512" alt="스크린샷 2024-10-06 오후 9 59 02" src="https://github.com/user-attachments/assets/0ea5f988-baa3-4a73-91e0-a9780da97754">

## ✅ 체크 리스트

- [ ] 리뷰어 설정했나요?
- [ ] Label 설정했나요?
- [ ] 제목 양식 맞췄나요? (ex. RAC-1 feat: 기능 추가)
- [ ] 변경 사항에 대한 테스트 진행했나요?
- [ ] `npm run format:fix` 실행했나요?

2024-10-06 14:23 UTC, leehyewon0531 requested changes
수고 많으셨습니당!!! 🫡🫡🫡
**로컬에서 `npm run build` 하고 배포 오류 뜨면 해결하고 올려주실 수 있나요?! 저번에 배포 오류 해결하는 데 좀 애를 먹어서 각자 코드에 있는 배포 오류는 각자가 해결하면 좋을 것 같습니다!!**
- lint 오류 중에 `Warning`이라고 뜨는 건 해결하지 않아도 괜찮습니다
- 그리고 되도록이면 기능이나 페이지별로 브랜치 구분해서 PR 날려주시면 좋겠습니다 ㅠㅠ!!
- lint 오류 그럼 해결 안 된 것도 다 disable 처리는 되어 있는 거죠...?! 안 그러면 배포를 할 수 없어서 여쭤봅니다!
- 대시보드 페이지로 이동하면 콘솔에 오류가 몇개 뜨던데 다 처리된 걸까요...?! 캡쳐화면 하단에 오류가 몇개 있는 것 같아서 혹시나 해서 여쭤봅니다!!!

2024-10-06 14:23 UTC, leehyewon0531 commented on src/app/focus/page.tsx
> +    getAccessToken()
react-query 안 쓰고 그냥 axios 쓴 이유는 시간이 오래 걸려서인가요??

2024-10-06 14:23 UTC, leehyewon0531 commented on src/app/information/components/Recommend/Recommend.tsx
>                  카페를 좋아하는 성현님을 위한 카페 추천
여기 이름 하드코딩 된 거 바뀌어야 할 것 같습니다!

2024-10-06 14:23 UTC, leehyewon0531 commented on src/app/information/components/Recommend/Recommend.tsx
>                카페를 좋아하는 성현님을 위한 카페 추천
여기두영!

2024-10-06 14:23 UTC, leehyewon0531 commented on src/app/information/components/Todo/Todo.tsx
> +import { useSearchParams } from 'next/navigation';
useSearchParams 슬랙에서도 말했듯이 Suspense 없이 사용하면 배포 오류 납니다! `FocusSearchParams`처럼 클라이언트 컴포넌트로 분리해서 불러오는 형식으로 사용해야 합니다

2024-10-06 14:23 UTC, leehyewon0531 commented on src/app/information/components/Todo/Todo.tsx
> +  onClickVacation,
optional로 받을 거면 디폴트값을 지정해주는 게 좋을 것 같아요 `onClickVacation: () => {}` 이런 식으로??

2024-10-06 14:23 UTC, leehyewon0531 commented on src/app/information/components/Todo/Todo.tsx
> +  const [VacationArr, setVacationArr] = useState<TodoTime[]>([]);
상태변수명 카멜 케이스가 아니라 파스칼 케이스로 작성하신 이유가 있나요?.? 린트 오류 안나던가요?

2024-10-06 14:23 UTC, leehyewon0531 commented on src/app/information/components/Todo/Todo.tsx
> +        window.location.reload();
여기 reload는 왜 있는 건가용??

2024-10-06 14:23 UTC, leehyewon0531 commented on src/app/information/components/Todo/Todo.tsx
> +          `${process.env.NEXT_PUBLIC_SERVER_URL}/api/dashboard/todo/1`,
여기 '1' 고정인가요?? day를 유동적으로 받을 수 있게 수정되어야 할 것 같아요!

2024-10-06 14:23 UTC, leehyewon0531 commented on src/app/information/components/Todo/Todo.tsx
> +  }, [getAccessToken]);
이거 `getAccessToken` 빼셔도 됩니다..! 린트 Error가 아니라 Warning일 거예요

2024-10-06 14:23 UTC, leehyewon0531 commented on src/app/information/mypage/page.tsx
> +    alert('아직 준비중인 기능 입니다.');
탈퇴 근데 api에 토큰만 쏘면 되지 않나요...?! 로직 구현할 게 딱히 업슬거 같은데.. 근데 중요한 기능은 아니라 없어도 될 것 같긴 합니다

2024-10-06 14:23 UTC, leehyewon0531 commented on src/app/information/quration/page.tsx
> +  const activity = '카공';
여기도 api 연결 나중에 하는 건가요??

2024-10-06 14:23 UTC, leehyewon0531 commented on src/app/information/retrospect/page.tsx
> +            day 1
뭔가 전체적으로 날짜가 다 day 1 고정인 것 같은데 워케이션 기간 받아서 오늘 날짜로 지금이 며칠째인지 계산하는 유틸이 하나 있어야 할 것 같아요

2024-10-06 14:23 UTC, leehyewon0531 commented on src/components/Modal/Modal.tsx
> +  end?: boolean;
이 props들 optional로 받아야 하는 이유가 있나요?! 웬만하면 optional로 안 받는 게 좋을 것 같은데! 이유가 있어서 optional로 받는다 해도 디폴트값을 다 지정해주는 게 좋을 것 같아요

2024-10-06 14:23 UTC, leehyewon0531 commented on src/components/TodoModal/TodoModal.tsx
> +                `${process.env.NEXT_PUBLIC_SERVER_URL}/api/dashboard/vacation/todo/fin/1`,
여기도 day가 유동적인 값이어야 할듯...ㅜㅜ

2024-10-06 14:23 UTC, leehyewon0531 commented on src/components/TodoModal/TodoModal.tsx
> +            `${process.env.NEXT_PUBLIC_SERVER_URL}/api/dashboard/vacation/todo/fin/1`,
여기두여!!

2024-10-06 14:23 UTC, leehyewon0531 commented on src/store/useTodoIdStore.ts
> +  id: null,
여기 받는 쪽에서 null 처리 다 되어 있나요?? 초기값이 null이면 오류날 수도 있을 것 같은데

2024-10-06 14:23 UTC, leehyewon0531 commented on src/types/timeRange.type.ts
> +export type CoreTimeType = {
여기 TimeRangeResponseType이랑 CoreTimeType이 속성이 다 똑같은데 2개가 따로 있어야 하나요??

2024-10-09 05:01 UTC, yeonsuu21 commented on src/app/focus/page.tsx
> +    getAccessToken()
넵 맞습니다 ! ㅠㅠ

2024-10-09 05:02 UTC, yeonsuu21 commented on src/types/timeRange.type.ts
> +export type CoreTimeType = {
이부분 키값 통일 제안하기전에 만들어놨던건데 수정하면서 쓰지 않게된 타입입니다 ! 삭제하겠슴다 !

2024-10-09 05:07 UTC, yeonsuu21 commented on src/store/useTodoIdStore.ts
> +  id: null,
넵 되어있습니다 !

2024-10-09 05:09 UTC, yeonsuu21 commented on src/components/Modal/Modal.tsx
> +  end?: boolean;
end와 id가 들어가는 경우가 한가지만 있어서 optional로 설정해놨습니당

2024-10-09 05:30 UTC, yeonsuu21 commented on src/app/focus/page.tsx
> +  const intervalIdRef = useRef<number | null>(null); // interval ID를 ref로 관리
초기 진입시 state로 하게되면 계속 진입시간이 갱신되어서 초기 진입에서만 값을 저장하려고 useRef를 사용했습니당

2024-10-09 05:49 UTC, yeonsuu21 commented on src/app/information/quration/page.tsx
> +  const activity = '카공';
넵 맞습니다 이부분 디자인 워딩이 좀 바뀌어서 그거에 맞춰서 수정할것같습니다

2024-10-09 05:50 UTC, yeonsuu21 commented on src/app/information/mypage/page.tsx
> +    alert('아직 준비중인 기능 입니다.');
쏘면되긴하는데 지도 부분을 우선적으로 작업하면 좋겠다구 하셔서 후순위로 하기로했습니당 일단은 작업전에 alert로 하고 작업 들어가면 없애고 api연결 할 생각입니다

2024-10-09 05:51 UTC, yeonsuu21 commented on src/app/information/components/Todo/Todo.tsx
> +  }, [getAccessToken]);
수정했습니다 ~

2024-10-09 05:51 UTC, yeonsuu21 commented on src/app/information/components/Todo/Todo.tsx
> +          `${process.env.NEXT_PUBLIC_SERVER_URL}/api/dashboard/todo/1`,
수정했습니다 ~!

2024-10-09 05:54 UTC, yeonsuu21 commented on src/app/information/components/Todo/Todo.tsx
> +        window.location.reload();
post 요청을 보내고 다시 get요청을 가져오는 과정에서 새로고침을 넣으려고 했던건데 useEffect 배열 의존성 넣는걸로 해결했습니다 ! 해당 부분 지우는걸로 수정했습니당

2024-10-09 05:55 UTC, yeonsuu21 commented on src/app/information/components/Todo/Todo.tsx
> +  const [VacationArr, setVacationArr] = useState<TodoTime[]>([]);
엇 이부분 오류는 안났는데 이상하네여...?! 소문자로 수정했습니당

2024-10-09 05:58 UTC, yeonsuu21 commented on src/app/information/components/Todo/Todo.tsx
> +  onClickVacation,
해당 부분 optional로 받지 않는걸로 수정했습니당

2024-10-09 06:06 UTC, yeonsuu21 commented on src/app/information/components/Todo/Todo.tsx
> +import { useSearchParams } from 'next/navigation';
해당부분 useSearchParams 사용하는게 아닌 토글 선택값 store로 저장해서 구분하는걸로 바꾸었습니다 ! import부분도 삭제 했습니당

2024-10-09 06:19 UTC, merged