OFZ-9 feat: Recap 페이지 디테일 중간pr
WORK-NECTOR/OFFIZZ-FE pull request #7
Opened 2024-07-23 05:45 UTC by yeonsuu21

## 🍋 PR 요약
Recap 페이지 디테일 중간pr
## ✨ PR 상세 내용
Recap 페이지 디테일 중간pr

-> 타입이랑 컴포넌트 쪼개기 한번 봐주세요..! 
-> recap 페이지에서 module.css 썼는데 어떤가요? 
## 🚨 주의 사항
리캡 페이지 내부 텍스트 하드코딩(데이터 연결하면 map으로 바꿀 예정)
리캡 페이지 재생 아이콘 디자이너분에게 합친 아이콘 전달받은 후 넣을예정입니다!
## 📸 스크린샷
[
<img width="1511" alt="스크린샷 2024-07-23 오후 2 42 04" src="https://github.com/user-attachments/assets/9aae447b-ecf9-4ec9-9cac-c4bb74b0f672">
](url)
## ✅ 체크 리스트

- [ ] 리뷰어 설정했나요?
- [ ] Label 설정했나요?
- [ ] 제목 양식 맞췄나요? (ex. RAC-1 feat: 기능 추가)
- [ ] 변경 사항에 대한 테스트 진행했나요?
- [ ] `npm run format:fix` 실행했나요?

2024-07-23 07:40 UTC, leehyewon0531 requested changes
굿!!!! 제가 파일 구조를 너무 제 입맛대로만 짠 것 같은데 잘 따라와주셔서 감사합니다 ㅠ_ㅠ 개인적으로 Title 컴포넌트는 없애구 TitleDesc 컴포넌트를 확장해서 사용하는 게 좋을 것 같아서 건의 드립니다!! 🫡

2024-07-23 07:40 UTC, leehyewon0531 commented on src/components/Title/Title.tsx
저라면 이 컴포넌트보다는 `TitleDesc` 컴포넌트를 확장해서 사용할 것 같습니다! 이것도 결국 Title + Desc 를 보여주는 컴포넌트이기 때문에 저라면 지금 있는 TitleDesc 컴포넌트에서 Title, Desc 사이의 간격과 Title 글씨체, 컬러 등을 추가로 받는 prop을 추가해서 만들 것 같습니다...!!

2024-07-23 07:40 UTC, leehyewon0531 commented on src/app/globals.css
> +  --black-title: #1e1e1e;
이거는 디자인 시스템에는 없던데 실제 디자인에서는 쓰였군요...?! 건의를 드려봐야겠어요 👀

2024-07-23 07:40 UTC, leehyewon0531 commented on src/components/RecapBox/RecapBox.styled.ts
> +  }
중요한 건 아니지만 id 선택자 사용한 부분들 사이에 개행이 있으면 가독성이 더 좋을 것 같습니다! 저라면 7/8줄, 13/14줄, 22/23줄 사이에 개행을 줄 것 같습니다!!

2024-07-23 07:40 UTC, leehyewon0531 commented on src/app/recap/page.tsx
> +import React, { Fragment } from 'react';
Fragment를 import 했다가 최종 코드에서는 사용하지 않으신 것 같은데 eslint에서 오류 안 뱉던가요?.?

2024-07-23 07:40 UTC, leehyewon0531 commented on src/types/titleDesc.type.ts
> +  sort?: SortMethod;
TitleDesc에서도 사용하고 있는 props이기 때문에 optional로 바꾸기보다는 Title 컴포넌트를 쓸 때도 그냥 'left'를 기본값으로 지정해주면 좋을 것 같아요!! 근데 전 개인적으로 Title 컴포넌트 말고 TitleDesc 컴포넌트 확장에서 써야 할 것 같습니닷...!!!

2024-07-23 07:40 UTC, leehyewon0531 commented on src/types/recap.type.ts
Recap 컴포넌트화 넘 잘하셨네요!!! 😳😳 굿굿

2024-08-12 16:13 UTC, yeonsuu21 commented on src/components/RecapBox/RecapBox.styled.ts
> +  }
굿 !!!! 수정했습니다 !

2024-08-12 16:14 UTC, yeonsuu21 commented on src/app/recap/page.tsx
> +import React, { Fragment } from 'react';
넵 ㅠ 따로 안뱉는것가타요 ••

2024-08-12 16:22 UTC, yeonsuu21 commented on src/types/titleDesc.type.ts
> +  sort?: SortMethod;
넵 수정했습니다 !!!! TitleDesc 컴포넌트로 이용해서 써도 같더라구요 !!! 통일하는게 좋을것같습니다!

2024-08-12 16:23 UTC, merged